upstream app_server {
    server unix:/var/www/transformo/gunicorn.sock fail_timeout=0;
}

server {
    listen 80;
    server_name your_ec2_public_ip_or_domain;

    client_max_body_size 4G;

    access_log /var/www/transformo/logs/nginx-access.log;
    error_log /var/www/transformo/logs/nginx-error.log;

    location /static/ {
        alias /var/www/transformo/static/;
    }

    location /media/ {
        alias /var/www/transformo/media/;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_buffering off;

        if (!-f $request_filename) {
            proxy_pass http://app_server;
            break;
        }
    }

    # Error pages
    error_page 500 502 503 504 /500.html;
    location = /500.html {
        root /var/www/transformo/static/;
    }
}
