[program:transformo]
# The gunicorn_start.sh script is stored in the repository under deployment/
# Supervisor should run the script from its repository location.
command = /var/www/transformo/deployment/gunicorn_start.sh
user = ubuntu
stdout_logfile = /var/www/transformo/logs/supervisor.log
redirect_stderr = true
environment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8
autostart=true
autorestart=true
